[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  ElectronicCats/MPU6050 @ ^1.0.0
  kosme/arduinoFFT @ ^1.6.1
  bblanchon/ArduinoJson @ ^6.21.3
